package thw.edu.javaII.port.warehouse.model.deo;

public enum Command {
    ADD, DELETE, INIT, LIST, UPDATE, SEARCH, GETBYMODEL, BESTAND, TOP, LOW, CLOSE, END, GETBYID, FILTER, GETNEXTID, ADD_WITH_BESTAND,
    REORDER_CREATE, REORDER_CONFIRM, REORDER_REJECT, REORDER_LIST
}